### ISSUE TITLE
Move Monte Carlo functionality from bugSetEnrichment

### ISSUE THREAD

**Issue by lwaldron** [waldronlab/bugSigSimple#1]
Related to https://github.com/waldronlab/bugSetEnrichment/issues/11

Move all functionality from https://github.com/waldronlab/bugSetEnrichment/blob/master/R/bugsigdb_analyses.R (except for importBugSigDB) to this repo.

https://github.com/waldronlab/bugSetEnrichment/blob/d6ab1fdca906f8af0f7dd1f7920360c69b387a1c/R/bugsigdb_analyses.R#L41-L159

**Comment by cmirzayi** [comment]
Added in https://github.com/waldronlab/bugSigSimple/commit/e48050df6c5073c290084b5d0eafce412a68ff44
