### ISSUE TITLE
replace subsetByCondition with bugsigdbr::subsetByOntology

### ISSUE THREAD

**Issue by lwaldron** [waldronlab/bugSigSimple#15]
subsetByCondition is no longer needed as bugsigdbr::subsetByOntology is more powerful and is part of a standard Bioconductor package. This would involve:

- [x] replacing use of subsetByCondition in all the current vignettes
- [x] making sure the vignettes still build correctly (some small changes in included signatures would be OK)
- [x] removing the subsetByCondition function from this repo

**Comment by cmirzayi** [comment]
@lkasselman and I tackled these this afternoon.
