### ISSUE TITLE
cleanup this repo's current R directory

### ISSUE THREAD

**Issue by lwaldron** [waldronlab/bugSigSimple#2]
Use importBugSigDB from waldronlab/bugsigdb repo. Depends on https://github.com/waldronlab/BugSigDB/issues/70

**Comment by cmirzayi** [comment]
Looks like we're going to use waldronlab/bugsigdbr according to discussion on waldronlab/BugSigDB#70

**Comment by lgeistlinger** [comment]
yes: `bugSigSimple` should depend on `bugsigdbr`, use

> bugsigdbr::importBugSigDB()

to bring in the data.

**Comment by cmirzayi** [comment]
Done in https://github.com/waldronlab/bugSigSimple/commit/418e38c1e8ca13e699fd208cc8d57ae1227a3dfe
