### ISSUE TITLE
cleanup vignettes/ and / directory

### ISSUE THREAD

**Issue by lwaldron** [waldronlab/bugSigSimple#3]
One vignette only, no extra files in root directory

**Comment by cmirzayi** [comment]
Vignettes have been cleaned up in https://github.com/waldronlab/bugSigSimple/commit/4d8aad1301c08b321a0c3459d3c38fd830e815c1

Only @ftzohra22 vignette remains which needs to be rewritten as an rmd. I will open a separate issue for this.
