### ISSUE TITLE
Update vignettes/capstoneanalysis_fatima.rmd

### ISSUE THREAD

**Issue by cmirzayi** [waldronlab/bugSigSimple#5]
Currently vignettes/capstoneanalysis_fatima.rmd is an .R file that was pasted into an .RMD without formatting or code blocks.

For instructions on formatting an RMD, see the RMD cheatsheet here: https://www.rstudio.com/wp-content/uploads/2015/02/rmarkdown-cheatsheet.pdf as well as tutorials available here: https://rmarkdown.rstudio.com/lesson-1.html

**Comment by lwaldron** [comment]
`usethis` has a function for creating a default vignette that would be
convenient. `biocthis` also has a function for creating a Bioconductor
vignette, but I don’t think this package is bound for Bioconductor.--

Levi Waldron

Associate Professor

Department of Epidemiology and Biostatistics

CUNY Graduate School of Public Health and Health Policy

Institute for Implementation Science in Population Health

55 W 125th St, New York NY 10035

https://waldronlab.io
